/// Regenerates boundary indexes and the CLDR metazone tables.
///
/// Maintainer playbook (which upstream → which command):
/// [`tool/docs/release-runbook.md`](docs/release-runbook.md).
///
///     dart run tool/refresh.dart --release 2026c            # regenerate
///     dart run tool/refresh.dart --release 2026c --verify   # check only
///
/// Triages the release, runs `tool/generate_data.dart` for the indexes, then
/// refreshes `lib/src/generated/metazone_data.dart` from CLDR and runs the suite.
/// The last two are skipped under `--verify`. The release is a parameter
/// rather than "latest" so any past one can be reproduced. Generated files are
/// committed; consumers never run this.
///
/// Three upstreams — only two are refreshed here:
///
/// - **TZBB** (`--release`) — Timezone Boundary Builder tag (e.g. `2026c`).
///   Named after a tzdb release it targets; this is the polygon dataset, not
///   IANA's transition rules.
/// - **CLDR** — always whatever is on `unicode-org/cldr-json` `main` today
///   (no CLDR pin on this CLI). For a CLDR-only bump, run
///   `tool/generate_metazone_data.dart` alone.
/// - **IANA tzdb** — not regenerated by this package. Offsets / DST / letter
///   abbreviations come from `package:timezone`; bump that dependency when
///   tzdb moves. Keep using `latest_all`.
///
/// Flags — the first three are passed through to `generate_data.dart`:
///
/// - `--release <tag>` (2026c) — the tzbb release to build.
/// - `--tolerance <units>` (1000, ~110 m) — simplification tolerance, the one
///   flag that changes what ships.
/// - `--chunk-kb <n>` (1024) — base64 chunk size; source layout only.
/// - `--verify` — rebuild and compare, writing nothing.
/// - `--no-tests` — skip the suite at the end.
///
/// **Byte-identity is claimed only for the same release and tolerance.**
/// `--verify` asserts that 2026c at the default tolerance regenerates 2026c's
/// committed boundary bytes exactly. A different release — or a different
/// `--tolerance` — *should* produce different bytes; that is not corruption.
library;

import 'dart:convert';
import 'dart:io';

import 'src/fetch.dart';

const String _usage =
    'Usage: dart run tool/refresh.dart [--release <tag>] '
    '[--tolerance <units>] [--chunk-kb <n>] [--verify] [--no-tests]';

Future<void> main(List<String> args) async {
  var release = defaultRelease;
  var verifyOnly = false;
  var chunkKb = 1024;
  // 1e-3 degrees, about 110 m: measured as the point where the coordinate
  // blob falls to 3.89 MB. Changing it changes what ships.
  var tolerance = 1000;
  var skipTests = false;
  // Value flags consume their value with `++i`, so a value can never be read
  // as a flag, and anything left unrecognised is a hard error. Silently
  // ignoring a typo here would regenerate the *default* release under a
  // command that names another one, and the diff would look like a no-op.
  for (var i = 0; i < args.length; i++) {
    final argument = args[i];
    // A following `--flag` is never a value: `--release --verify` means the
    // release was forgotten, not that it is named "--verify".
    final hasValue = i + 1 < args.length && !args[i + 1].startsWith('--');
    switch (argument) {
      case '--release' when hasValue:
        release = args[++i];
      case '--chunk-kb' when hasValue:
        final chunk = int.tryParse(args[++i]);
        if (chunk == null) {
          stderr.writeln(
            '--chunk-kb needs an integer, got ${args[i]}\n$_usage',
          );
          exitCode = 64;
          return;
        }
        chunkKb = chunk;
      case '--tolerance' when hasValue:
        final units = int.tryParse(args[++i]);
        if (units == null) {
          stderr.writeln(
            '--tolerance needs an integer, got ${args[i]}\n$_usage',
          );
          exitCode = 64;
          return;
        }
        tolerance = units;
      case '--verify':
        verifyOnly = true;
      case '--no-tests':
        skipTests = true;
      case '-h' || '--help':
        stdout.writeln(_usage);
        return;
      case '--release' || '--chunk-kb' || '--tolerance':
        stderr.writeln('Missing value for $argument.\n$_usage');
        exitCode = 64;
        return;
      default:
        stderr.writeln('Unknown argument: $argument\n$_usage');
        exitCode = 64;
        return;
    }
  }

  stdout.writeln('=== timezone_finder refresh: $release ===\n');

  if (!await _triageRelease(release, verifyOnly: verifyOnly)) {
    exitCode = 1;
    return;
  }

  // The indexes themselves are generate_data.dart's job, verify included: it
  // owns the build, so it is the only place that can compare a rebuild against
  // what is committed. Its output is inherited, so it reports its own failure.
  if (!await _run('dart', <String>[
    'run',
    'tool/generate_data.dart',
    '--release',
    release,
    '--tolerance',
    '$tolerance',
    '--chunk-kb',
    '$chunkKb',
    if (verifyOnly) '--verify',
  ])) {
    exitCode = 1;
    return;
  }
  if (verifyOnly) return;

  await _run('dart', <String>[
    'format',
    'lib/src/generated',
    'lib/src/generated/boundaries_bin.dart',
  ]);

  stdout.writeln('\nRefreshing CLDR metazone tables …');
  if (!await _run('dart', <String>[
    'run',
    'tool/generate_metazone_data.dart',
  ])) {
    stdout.writeln('\nFAIL — metazone data generation failed.');
    exitCode = 1;
    return;
  }
  await _run('dart', <String>[
    'format',
    'lib/src/generated/metazone_data.dart',
  ]);

  if (!skipTests) {
    stdout.writeln(
      '\nRunning the suite — regenerated data must not land '
      'unverified …',
    );
    if (!await _run('dart', <String>['test'])) {
      stdout.writeln(
        '\nFAIL — tests did not pass against the regenerated '
        'data. Do not commit it.',
      );
      exitCode = 1;
      return;
    }
  }

  stdout.writeln(
    '\nDone. This run wrote lib/src/generated/, lib/src/generated/boundaries_bin.dart, '
    'lib/data/ and tool/release/ — review all four before committing, and '
    'record the release in CHANGELOG.md.',
  );
}

/// Compares the release's identifier list against the committed one.
///
/// A few kilobytes, fetched before the 51 MB archive. It settles whether the
/// identifier set moved, not whether answers did — geometry alone can change
/// answers with the set unchanged.
Future<bool> _triageRelease(String release, {required bool verifyOnly}) async {
  stdout.writeln('Triage — comparing identifiers against the committed set …');
  final url = Uri.https(
    'github.com',
    '/evansiroky/timezone-boundary-builder/releases/download/'
        '$release/timezone-names.json',
  );

  List<String> incoming;
  try {
    incoming = await _fetchNames(url);
  } on Object catch (error) {
    stdout.writeln('  could not fetch $url: $error');
    return false;
  }

  if (!committedNamesFile.existsSync()) {
    stdout.writeln(
      '  no committed baseline yet; recording ${incoming.length} '
      'identifiers',
    );
    return true;
  }

  final committed =
      json.decode(committedNamesFile.readAsStringSync())
          as Map<String, Object?>;
  final committedRelease = committed['release'] as String;
  final committedList = <String>[
    for (final name in committed['names']! as List<Object?>) name! as String,
  ];

  stdout.writeln(
    '  committed data is $committedRelease, '
    'you asked for $release',
  );

  final added = incoming.toSet().difference(committedList.toSet()).toList()
    ..sort();
  final removed = committedList.toSet().difference(incoming.toSet()).toList()
    ..sort();

  if (added.isEmpty && removed.isEmpty) {
    stdout.writeln(
      '  identifier set unchanged (${incoming.length}) — any '
      'change is geometry only, so a patch release',
    );
  } else {
    stdout
      ..writeln(
        '  IDENTIFIER SET CHANGED — this can change answers users '
        'depend on. Minor release, and a changelog entry.',
      )
      ..writeln('    added:   ${added.isEmpty ? '(none)' : added.join(', ')}')
      ..writeln(
        '    removed: '
        '${removed.isEmpty ? '(none)' : removed.join(', ')}',
      );
    if (verifyOnly && committedRelease != release) {
      stdout.writeln(
        '  (--verify against a different release will fail by '
        'design; byte-identity is only claimed release-for-release)',
      );
    }
  }
  return true;
}

Future<List<String>> _fetchNames(Uri url) async {
  final client = HttpClient();
  try {
    var request = await client.getUrl(url);
    var response = await request.close();
    // GitHub redirects release assets to a CDN.
    var hops = 0;
    while (response.isRedirect && hops++ < 5) {
      final location = response.headers.value(HttpHeaders.locationHeader)!;
      await response.drain<void>();
      request = await client.getUrl(url.resolve(location));
      response = await request.close();
    }
    if (response.statusCode != 200) {
      throw HttpException('HTTP ${response.statusCode}');
    }
    final body = await response.transform(utf8.decoder).join();
    return <String>[
      for (final name in json.decode(body) as List<Object?>) name! as String,
    ];
  } finally {
    client.close();
  }
}

Future<bool> _run(String executable, List<String> arguments) async {
  stdout.writeln('\n\$ $executable ${arguments.join(' ')}');
  final process = await Process.start(
    executable,
    arguments,
    mode: ProcessStartMode.inheritStdio,
  );
  return await process.exitCode == 0;
}
